version: "3"
services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      - HTTP_USER=cerquide
      - HTTP_PASS=elena666
    volumes:
      - ./dnsmasq.leases:/var/lib/misc/dnsmasq.leases
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.log:/var/log/dnsmasq.log
      - ./static_hosts:/etc/hosts
      - ./ad.list:/etc/ad.list
      - /etc/localtime:/etc/localtime:ro
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart dnsmasq; done"]
    restart: unless-stopped

